### ISSUE TITLE
How to handle file download on form submission?

### ISSUE THREAD

**Issue by dgmdan** [FriendsOfPHP/Goutte#120]
I'm using Goutte to submit a form where the response isn't an HTML page but rather a MS Excel file.  Specifically the response has these headers:

Content-Type: application/vnd.ms-excel
Content-Disposition: attachment; filename="stuff.xls"

How can I access the contents of this file?

**Comment by kojca-mmye** [comment]
Sorrry, Now. How to handle it
 Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Symfony\Component\DomCrawler\Crawler::getResponse()

**Comment by humansix** [comment]
@kojca-mmye use crawler like this :
`
$crawler = $client->submit($myForm)
$client->getResponse()->getContent());
`
