### ISSUE TITLE
Any way to access Guzzle response

### ISSUE THREAD

**Issue by canvural** [FriendsOfPHP/Goutte#134]
Hello,

I'm trying to access to Guzzle response because i want to get the effective url.

Currently, as far as i can see, there is absolutely no way to access the response. Why?!!

**Comment by pedroskakum** [comment]
I have the same problem, after submit form login, I'm not logged, i can't get response data or session

**Comment by dpde** [comment]
Try to call `getUri()` on your crawler to get the effective url. The response can be accessed via `getResponse()` on the client.

Example
```
use Goutte\Client;

$client = new Client();
$crawler = $client->request('GET', 'http://domain.com');

// Effective Url
echo $crawler->getUri();

// Response
var_dump($client->getResponse());


```
