### ISSUE TITLE
How to simulate javascript support?

### ISSUE THREAD

**Issue by gustavomanolo** [FriendsOfPHP/Goutte#175]
Hi, i'm trying to submit a form inside a webpage that first checks for javascript browser support/enabled, if doesn't it wont display the content of the form, so i'm trying to know how to simulate the browser enabled.

The fact is that when i make s simple guzzle request with allow_redirects options disabled, i get the form that i need:
```
$URL = 'https://facturacion.walmartmexico.com.mx/';
$client = new GuzzleHttp\Client();
$response = $client->get($URL, ['allow_redirects' => false]);
echo $response->getBody();
```

Here's the code that i'm using with Goutte Client:
```
$URL = 'https://facturacion.walmartmexico.com.mx/';
$client = new \Goutte\Client();
$client->getClient()->setDefaultOption('config', ['curl' => ['CURLOPT_TIMEOUT' => 60, 'CURLOPT_FOLLOWLOCATION' => false]]);
$crawler = $client->request('GET', $URL);

echo $client->getResponse()->getContent();
```

**Comment by fabpot** [comment]
Closing as there is no activities here.
