### ISSUE TITLE
Bad phar causes class/trait not found errors.

### ISSUE THREAD

**Issue by ssanders** [FriendsOfPHP/Goutte#183]
I got the [new phar](http://get.sensiolabs.org/goutte.phar) and get random class or trait not found errors. My [old phar](http://dev3.propertypreswizard.com/lib/goutte/goutte.phar) from July works.
```php
$client = new GuzzleHttp\Client([
	'base_url' => 'http://imallaboutthatguzzle.com',
	'defaults' => [ 'cookies' => true ]
]);
```

**Comment by fabpot** [comment]
I've checked on my side and everything works as expected, even if I put the phar in another directory. I've also checked that the phar is the latest version of Goutte 2. So, I'm closing this issue for now, feel free to reopen if you can tell us a way to reproduce the issue. Thanks.
