### ISSUE TITLE
How to upload file with Guzzle client?

### ISSUE THREAD

**Issue by stuzzo** [FriendsOfPHP/Goutte#198]
I'm trying to do BDD testing on an upload method. I'm using Behat with Mink in a symfony2 project.
I'm trying to use the Guzzle client to send a form with file.

```php
$url = $this->minkParameters["base_url"] . '/' . ltrim($url, '/'); 
$file = new \Symfony\Component\HttpFoundation\File\UploadedFile($path, "video");
$fields = json_encode($table->getColumnsHash()[0]); //array("user" => "test")
$this->client->request("POST", $url, array('content-type' => 'multipart/form-data'), array($file), array(), $fields);
```
I receive this error:

```php
Call to undefined method GuzzleHttp\Stream\Stream::addFile()
```
Where am i wrong?
Thank you

**Comment by stof** [comment]
which version of Guzzle are you using ?

**Comment by stuzzo** [comment]
I didn't specify a particolar version, I installed these:

```javascript
"behat/symfony2-extension": "~2.0@dev",
"phpunit/phpunit": "4.4.1",
"behat/mink-extension": "~2.0@dev",
"behat/mink-browserkit-driver":  "~1.1@dev",
"behat/mink-goutte-driver": "*",
"behat/mink-selenium2-driver":  "~1.1" 
```
Should I modify something?

**Comment by stuzzo** [comment]
I added these:

```javascript
"fabpot/goutte": "2.0.2",
"guzzlehttp/guzzle": "4.2.3"
        
```
And modified this:

```javascript
"behat/mink-goutte-driver": "1.1.0"
```
but I receive same error.

**Comment by stof** [comment]
even when you don't specify a specific version, you are still *using* a specific version (the one being in your lock file, which can also be known by using ``composer show -i guzzlehttp/guzzle``

**Comment by stuzzo** [comment]
Hi, I'm using 4.2.3 version, but I figured out what's going on.
When I get the client I use this:

```php
$this->client = $this->mink->getSession('goutte')->getDriver()->getClient();
```
The problem is that client is instance of \Behat\Mink\Driver\Goutte\Client instead of Guzzle.
So I changed my code:

```php
$this->client = $this->mink->getSession('goutte')->getDriver()->getClient()->getClient();
```
and now I can do this:

```php
$request = $this->client->createRequest("POST", $url);
$request->getBody()->replaceFields($fields);
$request->getBody()->addFile(new PostFile('test.mp4', fopen($path, 'rb')));
$response = $this->client->send($request);
```
But it's the right way?

**Comment by stuzzo** [comment]
I answer myself: NO, because all my methods shared in contexts fails due the fact that Guzzle Client has different interface respect Goutte Client.
Can you suggest me a solution to use the code posted in my first message?

Thank you.

**Comment by stuzzo** [comment]
Hi, I think I found the problem.
The file Goutte\Client at line 115, it creates the request and the type of object returned is GuzzleHttp\Message\RequestInterface.
Later in the method addPostFiles this line
```php
$request->getBody()->addFile(new PostFile($name, fopen($info, 'r')));
```
throws the error because $request->getBody() returns an object with type GuzzleHttp\Stream\StreamInterface that hasn't the method addFile. I think that the correct type should be GuzzleHttp\Post\PostBodyInterface when you want add files.
Am I correct?

**Comment by stuzzo** [comment]
I hope this can be useful for others. If you want add files in the raw body data, this is the correct way:
```php
 $fields = array("user" => "test");
 $fields["file"] = fopen('/path/to/file', 'rb');
 $this->client->request("POST", $url, array('Content-Type => multipart/form-data'), array(), array(), $fields);
```

**Comment by Vincent030299** [comment]
ok

**Comment by egeogretmen** [comment]
For the ones who stumble into this issue while trying to upload files:
As documented [here](http://docs.guzzlephp.org/en/latest/quickstart.html#sending-form-files), you should put your form data with files as shown below
```php
$response = $client->request('POST', 'http://httpbin.org/post', [
    'multipart' => [
        [
            'name'     => 'field_name',
            'contents' => 'abc'
        ],
        [
            'name'     => 'file_name',
            'contents' => fopen('/path/to/file', 'r')
        ],
        [
            'name'     => 'other_file',
            'contents' => 'hello',
            'filename' => 'filename.txt',
            'headers'  => [
                'X-Foo' => 'this is an extra header to include'
            ]
        ]
    ]
]);
```

**Comment by marcellopato** [comment]
But how to do it if the file is on the user's machine? I don´t know the full path to the file he wants to upload!

`'contents' => fopen('/path/to/file', 'r')`

If I do `'contents' => fopen($request->file, 'r')` the error is:
`: failed to open stream: No such file or directory`

**Comment by marcellopato** [comment]
Hi @stof , the problem is that I can´t send the file that I´ve chosen from my input file form.
fopen() can´t find it withou the whole path

**Comment by stof** [comment]
The question is whether `$request->file` is actually the absolute path of the file on your server. As we don't know what your `$request` is, we canot help you.

**Comment by ijain** [comment]
In my case, I should accept json data from user in API request, along with local path to a file. There is no way to upload file, no form, only raw data. Not sure how it is going to work. May be I will ask user to convert image to base64 and then pass data to me. Not sure how to get user's local file contents through my API.
Probably @marcellopato tried to do the same thing one year ago.
