### ISSUE TITLE
Can i Submit an Ajax form with goutte?

### ISSUE THREAD

**Issue by fofiedelly** [FriendsOfPHP/Goutte#199]
Hi, 
I'm crawling a website with Goutte, The login page is ajaxified, is it possible to handle it with goutte? if not do you know an alternative which could to that and send response to goutte?? 
Thanks in advance for your responses.

**Comment by stof** [comment]
There is no way to send an *AJAX* form in Goutte, because the J in AJAX means Javascript, and goutte is a PHP crawler, which does not know how to run JS.
Crawling a site with goutte is similar to browsing your site with JS disabled

**Comment by fofiedelly** [comment]
thanks @stof .

**Comment by ssanders** [comment]
If you view the site with say Firebug and see what the Ajax is doing, you can do the same with Goutte.

**Comment by fofiedelly** [comment]
:100: Thanks @ssanders i've just follow all ajax requests an it's works!! Thanksss!!
