### ISSUE TITLE
Unable to scrape google images

### ISSUE THREAD

**Issue by 3zzy** [FriendsOfPHP/Goutte#200]
I'm trying to scrape google for [reverse image search][1] results:

    $googleURL = "https://www.google.com/searchbyimage?&image_url=".$imageURL;
    
    $crawler = $client->request('GET', $googleURL);
    $client->followRedirects(true);
    print_r($crawler,1);

.. and the output (https://paste.ee/p/spfYA) contains the correct URL but the `body` (HTML) is of the default search page, the one without results.

What should I do to get the search results as HTML?

  [1]: http://stackoverflow.com/questions/28378354/reverse-image-scraping-with-php

**Comment by larowlan** [comment]
Sounds like you need a JavaScript capable solution, try Zombie or Phantom
