### ISSUE TITLE
I am unable to install ApiGen om a mac

### ISSUE THREAD

**Issue by MathijsvVelde** [FriendsOfPHP/Goutte#201]
I am unable to install ApiGen om a mac.
I did everything as instructed on apigen.org:

    wget http://apigen.org/apigen.phar
    chmod +x apigen.phar
    mv apigen.phar /usr/local/bin/apigen
    apigen --version
And this is the result I get everytime!

    sh-3.2# wget http://apigen.org/apigen.phar
    --2015-02-12 16:20:30--  http://apigen.org/apigen.phar
    Resolving apigen.org... 192.30.252.153
    Connecting to apigen.org|192.30.252.153|:80... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: /apigen.phar [following]
    --2015-02-12 16:20:30--  http://apigen.org/apigen.phar
    Connecting to apigen.org|192.30.252.153|:80... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: http://www.apigen.org/apigen.phar [following]
    --2015-02-12 16:20:30--  http://www.apigen.org/apigen.phar
    Resolving www.apigen.org... 23.235.43.133
    Connecting to www.apigen.org|23.235.43.133|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 793275 (775K) [application/octet-stream]
    Saving to: 'apigen.phar'

    apigen.phar                       100%[===============================================================>] 774.68K  --.-KB/s   in 0.1s   

    2015-02-12 16:20:30 (5.51 MB/s) - 'apigen.phar' saved [793275/793275]

    sh-3.2# chmod +x apigen.phar
    sh-3.2# mv apigen.phar /usr/local/bin/apigen
    sh-3.2# apigen --version

    **Fatal error**: Uncaught exception 'PharException' with message 'zlib extension is required for gz compressed .phar file "/usr/local/bin/apigen"' in /usr/local/bin/apigen:11
    Stack trace:
    #0 /usr/local/bin/apigen(11): Phar::mapPhar('apigen.phar')
    #1 {main}
      thrown in /usr/local/bin/apigen on line 11
Can some one tell me what i'm doing wrong.

thanks
Ps.: The question on Stackoverflow with this title is also mine

**Comment by stof** [comment]
why reporting this to the Goutte project ? It is not an issue with Goutte but with ApiGen

**Comment by MathijsvVelde** [comment]
oops!
wrong tab!!
