### ISSUE TITLE
Create a new release that allows Guzzle 5, 6

### ISSUE THREAD

**Issue by larowlan** [FriendsOfPHP/Goutte#202]
33b16e073667a3408b6a1e8c464614fbb731041a allowed guzzle 5 and 6 but there doesn't seem to be a release on packagist that contains this commit.
We're planning on bringing Goutte into Drupal core here: https://www.drupal.org/node/2433009 and would prefer not to rely on dev-master.

Thanks in advance
@larowlan

**Comment by fabpot** [comment]
2.0.3 has just been released now.

**Comment by larowlan** [comment]
thank you @fabpot for the fast turnaround
