### ISSUE TITLE
Passing Variables

### ISSUE THREAD

**Issue by mfrosch** [FriendsOfPHP/Goutte#203]
Hi,

I'm not able to pass a variable through, does anyone have a hint for me?

Here is an example:

	$foo = 'bar';
	$crawler->filter('#id')->each(function ($node) {
		var_dump($foo); // is empty and not 'abc'
	});	

Thanks in advance.

Cheers,
Matthias

**Comment by qferr** [comment]
Hi,

If you inherit variables in closure, try this:

```
$foo = 'bar';
$crawler->filter('#id')->each(function ($node) use($foo) {
    var_dump($foo); // is 'abc'
}); 
```

Php Documentation: [here](http://php.net/manual/en/functions.anonymous.php#example-186)

**Comment by mfrosch** [comment]
Great! Thank you : )
