### ISSUE TITLE
Support Guzzle 6

### ISSUE THREAD

**Issue by cilefen** [FriendsOfPHP/Goutte#215]
Guzzle 6.0.0 was just released https://github.com/guzzle/guzzle/releases

**Comment by vredeling** [comment]
Duplicate of https://github.com/laracasts/Integrated/issues/93

**Comment by fabpot** [comment]
anyone wanting to make it happen?

**Comment by csarrazi** [comment]
Done! Waiting for review :)

**Comment by fabpot** [comment]
3.0.0 with Guzzle 6.0 support is out. Thanks @csarrazi!

**Comment by cilefen** [comment]
Thank you @csarrazi.

**Comment by csarrazi** [comment]
You're welcome! :)
