### ISSUE TITLE
How to Crawl Ajax Site Data?

### ISSUE THREAD

**Issue by rashedshaon** [FriendsOfPHP/Goutte#216]
I want crawl a site which pagination's are loaded by by ajax. Is it possible to do this with Goutte?
I tried with,
$link = $crawler->selectLink('Next>')->link();
           $crawler = $client->click($link);
but not working.

**Comment by stof** [comment]
You can't if the site is not usable without Javascript, as Goutte is not able to run Javascript

**Comment by ssanders** [comment]
Use Firebug or similar to see what the Ajax loads, then get that with Goutte.

**Comment by stof** [comment]
well, if the goal is to crawl the site, the right solution would be to disable JS in your browser and browse the site to see how they support the case without JS.

**Comment by dunglas** [comment]
You can also try JS-enabled libraries or (sort of) headless browsers such as PhantomJS, SlimerJS or ZombieJS.
