### ISSUE TITLE
Get connect bases on previous HTML tag text

### ISSUE THREAD

**Issue by jitendrar** [FriendsOfPHP/Goutte#224]
I want to scrap a website which contain multiple div with same class and css. I want to parse a div based on its previous div text. Like previous div contains "Header" and next div contains "Detail description of that section". I want to scrap detail description if header contain specific text.

**Comment by ssanders** [comment]
```php
$detail = $crawler->filter('.class')->each(function ($node) use($prev) {
    if ($prev == 'Header') return trim($node->text());
    $prev = trim($node->text());
});
foreach ($detail as $v) if ($v) $details[] = $v;
var_dump($details);
```

**Comment by jitendrar** [comment]
It is working fine.. thanks...

**Comment by jayyugtia** [comment]
How to get Next "li" element using Goutte.

Please help me.
