### ISSUE TITLE
Can not use selectors

### ISSUE THREAD

**Issue by negreanucalin** [FriendsOfPHP/Goutte#227]
I tried to get some information from IMDB:
link : http://www.imdb.com/title/tt3148266/episodes?season=2
$page = $client->request('GET', 'http://www.imdb.com/title/tt3148266/episodes?season=2');
$page->filter('.wtw-option-standalone')->each(function ($node){ //there are allot of classes
    var_dump($node);  //is never printed 
});

**Comment by gmask** [comment]
This is a very old issue, but did you ever solve this? Using Goutte to scrape IMDb doesn't work at all for me, after a certain point I cannot access any DOM element at all.
