### ISSUE TITLE
Cookies for requests to hostnames with ports fails

### ISSUE THREAD

**Issue by joehoyle** [FriendsOfPHP/Goutte#232]
When calling `$client->doRequest()` the cookies in the cookie jar as set to be from the `HTTP_HOST` of the server for their domain. However, this breaks things is the `HTTP_HOST` has a port number, as cookies should be set against a `domain` not a hostname (which includes port number).

So far as I can tell, the problem lies in https://github.com/FriendsOfPHP/Goutte/blob/master/Goutte/Client.php#L95 where it uses the `HTTP_HOST` as the domain, instead this should somehow get the true domain, a quick hack would maybe to do `explode( ':', $request->getServer()['HTTP_HOST'] )[0]`.

**Comment by stof** [comment]
see #236
