### ISSUE TITLE
Goutte does not support php5

### ISSUE THREAD

**Issue by azizimusa** [FriendsOfPHP/Goutte#233]
Hi, recently I created droplet in digital ocean. Installed with PHP5, then upload my working project into it. View on browser display nothing but blank page.

**Comment by stof** [comment]
Well, goutte does not display anything by itself.

and without an error message, we cannot help you.
goutte works fine on PHP 5 (the 3.x versions of Goutte require at least PHP 5.5)

**Comment by azizimusa** [comment]
Hi, I was wrong. It turn out to be Curl does not installed yet, and updating Goutte thru composer, restarting Apache2. Then everything working fine.
