### ISSUE TITLE
Redirect Infinite Loop Fatal Error

### ISSUE THREAD

**Issue by nsanden** [FriendsOfPHP/Goutte#237]
This URL: http://teespring.com/herolife causes an infinite loop. Some sort of misconfiguration on their part. However, i'd like to catch that error instead of my script just timing out.

Code:
```php
        $client = new \Goutte\Client();
        $client->getClient()->setDefaultOption('config/curl/'.CURLOPT_TIMEOUT, 10);
        $client->getClient()->setDefaultOption('config/curl/'.CURLOPT_CONNECTTIMEOUT, 5);
        $client->request('GET', 'http://teespring.com/herolife');
```

Causes:
![72794ca8-560f-11e5-94d0-3d922ce0fe0b](https://cloud.githubusercontent.com/assets/2072064/9742993/bb118080-5618-11e5-8fb3-56d488ae52ac.png)

Following works fine though:
```php
        $client = new \GuzzleHttp\Client();
        $res = $client->get('http://teespring.com/herolife');
```
and causes error: 
```
GuzzleHttp\Exception\TooManyRedirectsException

Will not follow more than 6 redirects
```

**Comment by nsanden** [comment]
If I turn on xdebug the error is different:

```
Maximum function nesting level of '100' reached, aborting!
```

While it gives me the following 2 errors, over and over (100 times)
![yii base errorexception2](https://cloud.githubusercontent.com/assets/2072064/9743149/ae402c0c-5619-11e5-9cdc-030a43c84424.png)

**Comment by georaldc** [comment]
In Goutte, Symfony's browserkit component handles redirects and by default, its maxRedirects property is set to -1 (keep following redirects indefinitely). You can set this value yourself with the setMaxRedirects method.

```
$client = new \Goutte\Client();
$client->setMaxRedirects(5);
$client->request('GET', 'http://teespring.com/herolife');
```

This should throw a LogicException when the redirect limit is reached.

**Comment by nsanden** [comment]
Awesome thanks!
