### ISSUE TITLE
Duplicate User-Agent Headers

### ISSUE THREAD

**Issue by blakemckeeby** [FriendsOfPHP/Goutte#241]
The BrowserKit client sets the User-Agent header to 'Symfony2 BrowserKit' by default. When passing the header values to Guzzle, it fails to override the default Guzzle User-Agent header 'Guzzle/3.3.1 curl/7.35.0 PHP/5.6.3-1+deb.sury.org~trusty+1' which results in two User-Agent headers being put in the request:

User-Agent: Guzzle/3.3.1 curl/7.35.0 PHP/5.6.3-1+deb.sury.org~trusty+1
User-agent: Symfony2 BrowserKit

**Comment by fox000** [comment]
+1

**Comment by hao-li** [comment]
+1
