### ISSUE TITLE
How to get response status code?

### ISSUE THREAD

**Issue by bocharsky-bw** [FriendsOfPHP/Goutte#249]
I requested a page with Goutte client:

```php
$client = new Goutte\Client();
$crawler = $client->request('GET', 'http://symfony.com');
```

How can I get response status code of this request?

**Comment by stof** [comment]
``$client->getResponse()`` gives you the Response object

**Comment by bocharsky-bw** [comment]
Oh, I missing it because there's no autocompletion for this method :( . Thanks!

**Comment by stof** [comment]
well, there is autocompletion for me. If your autocompleter does not support PHP inheritance (to show methods defined in the parent class), I strongly suggest you to change your autocompleter

**Comment by bocharsky-bw** [comment]
I meant autocompletion for `Response`'s methods. Seems `getResponse()` returns `object|null` (see [BrowserKit's Client](https://github.com/symfony/browser-kit/blob/master/Client.php#L201), which inhereted by [Goutte's Client](https://github.com/FriendsOfPHP/Goutte/blob/master/Goutte/Client.php#L30)). So autocompliter can't resolve autocompletion of `getStatus()` without manual `@var` annotation like:

```php
        $client = new Goutte\Client();
        $crawler = $client->request('GET', 'http://symfony.com');

        /** @var \Symfony\Component\BrowserKit\Response $response */
        $response = $client->getResponse();
        $response->getStatus(); // can't get autocompletion here without @var above
```

**Comment by stof** [comment]
this is because ``getResponse`` was not designed properly first, and some implementation of browserkit might return another kind of object than the BrowserKit response. Symfony 2.3 added another getter ``getInternalResponse`` which is guaranteed to always return the browserkit response object

**Comment by bocharsky-bw** [comment]
Hm, seems I need a `getInternalResponse()`. @stof Thanks you for this info!

**Comment by pedzed** [comment]
Quite annoying that this isn't documented. After a lot of unnecessary searching:

```php
$client = new Goutte\Client();
$crawler = $client->request('GET', 'https://symfony.com');

$response = $client->getInternalResponse();
echo $response->getStatusCode(); // 200
```

**Comment by blare** [comment]
Thanks @pedzed, thats the correct way. You saved my day!
