### ISSUE TITLE
Lumen and Symfony CssSelector is not installed

### ISSUE THREAD

**Issue by lasselehtinen** [FriendsOfPHP/Goutte#253]
Hi,

I love your library and I have used it extensively before. I was trying to use it on Lumen microframework, but I can getting a strange autoloading problem with symfony/css-selector that I cannot figure out. 

Steps to reproduce:

1. composer create-project laravel/lumen goutte-test --prefer-dist
2. cd goutte-test/
3. composer require fabpot/goutte
4. Create app\Console\Commands\TestGoutte.php
5. Add command to commands array as '\App\Console\Commands\TestGoutte::class' in app\Console\Kernel.php
6. Run php artisan sample:command

This returns:

```
 [RuntimeException]
  Unable to filter with a CSS selector as the Symfony CssSelector is not installed (you can use filterXPath instead).
```

[Crawler checks that if the class is loaded](https://github.com/symfony/dom-crawler/blob/master/Crawler.php#L650), but some reason that is not the case with Lumen. I tested this on Laravel and it works fine. I cannot figure out what might be causing this Lumen or some strange Composer autoload problem.

https://gist.github.com/lasselehtinen/b754fffe3354132004c3#file-testgoutte-php

**Comment by karneds** [comment]
@lasselehtinen , add  `"symfony/css-selector":"^2.7"` in composer.json 

Lumen use `symfony/dom-crawler v2.7.7` and FriendsOfPHP/Goutte install `symfony/css-selector v.3.0.0` they are incompatible

**Comment by lasselehtinen** [comment]
@karneds Thanks for your input. First it did not work. Composer update did what it suppose to do but I still got the same error. Then removed composer.lock and removed vendor folder and did composer install. Then it worked just fine. Thanks a lot for your help!

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing symfony/css-selector (v3.0.0)
  - Installing symfony/css-selector (v2.8.0)
    Downloading: 100%
```

**Comment by rizqyhi** [comment]
I've got the same problem. Thanks.
