### ISSUE TITLE
Crawler fails if html contains \x00

### ISSUE THREAD

**Issue by justutiz** [FriendsOfPHP/Goutte#255]
Crawler delivers not full html if html contains \x00.

**Comment by aik099** [comment]
The NUL byte is a terminator after all. It's common behavior for string processing functions to stop processing a string after NUL byte is found.

@justutiz , 

1. what are you proposing as a solution?
2. is this normal for the page you're crawling to have NUL byte?

**Comment by justutiz** [comment]
At this moment I just use smth like this 

` 
$html = $client->getResponse();
$html = preg_replace('/[\x00-\x09]/', '', $html);
`

I don't know if it should be out of the box or it's just developer problem. Maybe put some notes in documentation that this can be an issue working with crawler?

**Comment by aik099** [comment]
Could you please find exact place (and write it down here) where NUL byte comes in, but as a result cut off string comes out. Maybe problem is in some other used library and not Goutte itself.

**Comment by justutiz** [comment]
I think that's BrowserKit problem. When BrowserKit converts response to Crawler instance it fails.

**Comment by aik099** [comment]
Can you please create issue in its repo, that would explain why such thing happens and reference it here?

**Comment by stof** [comment]
Actually, it is probably not even a BrowserKit issue but a PHP issue. BrowserKit just relies on PHP for the HTML parsing.
