### ISSUE TITLE
Error trying to make a request to a https url: "cURL error 60: SSL certificate problem"

### ISSUE THREAD

**Issue by daniegarcia254** [FriendsOfPHP/Goutte#258]
Hi,

I'm trying to make a request to this url [https://www.whoscored.com/?t=Hart](url), but I'm getting the following error:

`Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFa in C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187`

I know of course is related with the SSL connection, but I'm kind of lost in this aspect. I've made some search over the internet, but I haven't found a solution for the problem.

Could you help me with this? Some guide on how to solve the problem...

This is the code that make the request:

```
$client = new Client();

$url = 'http://www.whoscored.com/Search/?t=' . $player["name"];

$crawler = $client->request('GET', $url);
```

Is there anyway to make the call without a cert?

**Comment by ssanders** [comment]
Sorry, I did not realize you were using Goutte. After ```$client``` using Goutte 2 for example:
```php
$client->getClient()->setDefaultOption('config/curl/' . CURLOPT_SSL_VERIFYPEER, false);
```

**Comment by daniegarcia254** [comment]
I've already tried that at some point, and that line just give me this error:
`Catchable fatal error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, boolean given, called in C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Client.php on line 87 and defined in C:\xampp5.6\htdocs\comuniazo-uk\api\vendor\guzzlehttp\guzzle\src\Client.php on line 126`

**Comment by daniegarcia254** [comment]
Finaly I solved it with the answer given by @georaldc in #234 

[https://github.com/FriendsOfPHP/Goutte/issues/234#issuecomment-133579584](url)

**Comment by daniegarcia254** [comment]
Finaly I solved it with the answer given by @georaldc in #234 

[https://github.com/FriendsOfPHP/Goutte/issues/234#issuecomment-133579584](url)

**Comment by Maerryham** [comment]
please i have the same issue too and I need the solution. the link you provided does not any comment on it

**Comment by georaldc** [comment]
> please i have the same issue too and I need the solution. the link you provided does not any comment on it

His link is broken, but the link text is correct.

**Comment by daniegarcia254** [comment]
> please i have the same issue too and I need the solution. the link you provided does not any comment on it

Here's the link to that issue: https://github.com/FriendsOfPHP/Goutte/issues/234

**Comment by singi2016cn** [comment]
### work fell,like follow:
```
use Goutte\Client;
use GuzzleHttp\Client as GuzzleHttpClient;

$client = new Client();
$httpClient = new GuzzleHttpClient([
    'verify'=>false  //set 'verify=false'
]);
$client->setClient($httpClient);
```

### reference

```
http://docs.guzzlephp.org/en/stable/request-options.html#verify
```

**Comment by larowlan** [comment]
You probably don't want to do that, it effectively says 'I don't care if the SSL certificate is invalid or from a non-trusted CA, I trust the remote endpoint'.
