### ISSUE TITLE
Cannot push filter results to an array

### ISSUE THREAD

**Issue by Technopathic** [FriendsOfPHP/Goutte#266]
This is my attempt: 

    public function test() 
    {
        $result = array();
        $client = new Client();
        $crawler = $client->request('GET', 'http://hashcookie.net/uploads/-eac0a7ec83_test.html');
        $crawler->filter('h2')->each(function ($node){
            $result[] = $node->text();
        });
        return $result;
    }

Which returns an empty array. On the example, using  print $node->text()."\n"; inside of the crawler filter function does return data, but I plan on filtering other tags and adding them to the same results array. 
I saw and tried the fix in this issue: https://github.com/FriendsOfPHP/Goutte/issues/203 but there were no change in results. I am using PHP 5.5.9, Laravel 5.2, and Goutte 3.1.

Additionally, is it possible to filter out attributes such as: aria-label="foobar"?

**Comment by aik099** [comment]
Please replace `$crawler->filter('h2')->each(function ($node){` into `$crawler->filter('h2')->each(function ($node) use ($result) {`. Without this the `$result` variable isn't accessible to the closure.

**Comment by Technopathic** [comment]
@aik099 
```
public function test()
{
    $result = array();
    $client = new Client();
    $crawler = $client->request('GET', 'http://hashcookie.net/uploads/-eac0a7ec83_test.html');
    $crawler->filter('h2')->each(function ($node) use ($result) {
        $result[] = $node->text();
    });
    return $result;
}
```
It still returns an empty array.

**Comment by nesttle** [comment]
@Technopathic Thanks for this tip, worked for me!

But now I've other issue. I need to push items inside the each() loop, but no luck:
```
		$i=0;
	    $crawler->filter('th[class="a-span3 prodDetSectionEntry"]')->each(function($node,$i) use ($urls,$url,$result,$crawler) {
	    	if ($node->text() == 'OPT1') {
	    		$result['series'] = trim($crawler->filter('td[class="a-span a-align-center item"]')->eq($i)->text()); 
	    	} else { $result['series'] = 'a'; }

	    	if ($node->text() == 'OPT2') {
	    		$result['model'] = trim($crawler->filter('td[class="a-span a-align-center item"]')->eq($i)->text()); 
	    	} else { $result['model'] = 'b'; }

	    	if ($node->text() == 'OPT3') {
	    		$result['size'] = trim($crawler->filter('td[class="a-span a-align-center item"]')->eq($i)->text()); 
	    	} else { $result['size'] = 'c'; }
	    	$i++;
	    });
```

**Comment by nesttle** [comment]
Solved!

Changed this:
`        $crawler->filter('th[class="a-span th-product"]')->each(function($node,$i) use ($result,$crawler) {`

with this:
`        $crawler->filter('th[class="a-span th-product"]')->each(function($node,$i) use (&$result,$crawler) {`


`**&**$result`!!!!!!!!!!!!!

**Comment by Riteshagg** [comment]
This does not store the for each data in the variable Please help code is below:-

  public function scraping(){
        $url = $this->json();
        $data =[];

        foreach ($url['serps'] as $key=> $get){
            $client = new Client();
            $crawler = $client->request('GET', $get);
            $data[] =  $crawler->filter('h1')->each(function ($node) {
              return $node->text();
            });
        }
        dump($data);



    }

**Comment by jasonjflaherty** [comment]
Just want to give a simple example here using an array for any noobs like myself:

```
$myarray = array();
$crawler->filter('table table table table table a')->each(function ($node) **use (&$myarray,$crawler)**{
     $filtered = $node->attr('href');
     array_push($myarray,$filtered);
});
```
