### ISSUE TITLE
Can't install Goutte with Laravel 5.2

### ISSUE THREAD

**Issue by glaucomorais** [FriendsOfPHP/Goutte#268]
Composer output this:

> Problem 1
>     - Conclusion: don't install fabpot/goutte v3.1.2
>     - Installation request for guzzlehttp/guzzle (locked at 5.3.0) -> satisfiable by guzzlehttp/guzzle[5.3.0].
>     - Conclusion: remove symfony/css-selector v3.0.7
>     - Conclusion: don't install symfony/css-selector v3.0.7
>     - fabpot/goutte v3.1.0 requires symfony/css-selector ~2.1 -> satisfiable by symfony/css-selector[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7].
>     - fabpot/goutte v3.1.1 requires symfony/css-selector ~2.1 -> satisfiable by symfony/css-selector[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7].
>     - Can only install one of: symfony/css-selector[v2.8.0, v3.0.7].
>     - Can only install one of: symfony/css-selector[v2.8.1, v3.0.7].
>     - Can only install one of: symfony/css-selector[v2.8.2, v3.0.7].
>     - Can only install one of: symfony/css-selector[v2.8.3, v3.0.7].
>     - Can only install one of: symfony/css-selector[v2.8.4, v3.0.7].
>     - Can only install one of: symfony/css-selector[v2.8.5, v3.0.7].
>     - Can only install one of: symfony/css-selector[v2.8.6, v3.0.7].
>     - Can only install one of: symfony/css-selector[v2.8.7, v3.0.7].
>     - Installation request for symfony/css-selector (locked at v3.0.7, required as 2.8._|3.0._) -> satisfiable by symfony/css-selector[v3.0.7].
>     - Installation request for fabpot/goutte ^3.1 -> satisfiable by fabpot/goutte[v3.1.0, v3.1.1, v3.1.2].

**Comment by skvorets** [comment]
The same issue with Laravel 5.3. Latest Composer.
Goutte 1 installs fine. 
While trying to require version 3 or 2 of Goutte I get:

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: don't install fabpot/goutte v3.1.2
    - Conclusion: don't install fabpot/goutte v3.1.1
    - Conclusion: don't install fabpot/goutte v3.1.0
    - Conclusion: remove guzzlehttp/guzzle 5.3.1
    - Installation request for fabpot/goutte ^3.1 -> satisfiable by fabpot/goutte[3.1.x-dev, v3.1.0, v3.1.1, v3.1.2].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.1
    - fabpot/goutte 3.1.x-dev requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.x-dev, 5.3.1].
    - Installation request for guzzlehttp/guzzle (locked at 5.3.1) -> satisfiable by guzzlehttp/guzzle[5.3.1].

**Comment by fabpot** [comment]
Guzzle versions are a nightmare to manage, but there is nothing I can do. You should be able to use Goutte 1, 2, or 3 depending on your other dependencies.

**Comment by stof** [comment]
The Goutte API is the same in 1, 2 and 3 (as it is the BrowserKit API anyway), so it is indeed easy to support multiple versions)

**Comment by scruffycoder86** [comment]
Still cannot install this even today unfortunately. 

**Has the package been moved to a private repository?**

I am on Laravel 5.8 and below is my output:

_Steps to reproduce this would be to install it on a new Laravel 5.8 Framework codebase._
