### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by greatwitenorth** [FriendsOfPHP/Goutte#269]
How would you go about doing basic authentication for a request?

**Comment by greatwitenorth** [comment]
Answered my own question after digging through the code:
```
use Goutte\Client as CrawlerClient;

$crawlerClient = new CrawlerClient();
$crawlerClient->setServerParameter( 'http-Authorization', 'Basic myBase64encodedpassword==' );
```

**Comment by OGProgrammer** [comment]
There is a setAuth method right in the Goutte Client BTW, much cleaner

**Comment by greatwitenorth** [comment]
Thanks! I must have missed that.
