### ISSUE TITLE
Take snapshot of a web

### ISSUE THREAD

**Issue by raul2015** [FriendsOfPHP/Goutte#281]
It is possible to take a snapshot of the web loaded with Goutte ?

**Comment by fabpot** [comment]
If you mean a browser's screenshot, the answer is no as Goutte only makes HTTP requests without any client side rendering.

**Comment by raul2015** [comment]
Let me tell you a bit to see if you could point me in the right direction.
I need to be able to get the captcha image that shows on a certain web page but seems goutte doesn't wait for the captcha to load.

Regards

**Comment by fabpot** [comment]
Again, keep in mind that Goutte is only doing HTTP requests, so there is no "wait". You get the HTML page content, that's all. If you need the captcha, you probably need something else.

**Comment by stof** [comment]
the captcha is probably relying on some JS, and Goutte does not run the JS code
