### ISSUE TITLE
 slow the process down for big requests

### ISSUE THREAD

**Issue by mattiasghodsian** [FriendsOfPHP/Goutte#288]
Is there a way to slow the process for GET so the servers doesnt think im ddos them ?
`
                use Goutte\Client;
                use GuzzleHttp\Client as GuzzleClient;
                $client 	= new Client();
                $crawler = $client->request('GET', $url);
		$data = array();

		$crawler->filterXPath("//*[@itemprop]")
		    ->each(function($node) use (&$data){
		        $ret = $this->getStructuredData($node);
		        $data[$ret['property']] = $ret['value'];
		        sleep(5);
		    });

i would also like to know if i can leave a message in header or something to say where i came from (website url or name of company)?
`

**Comment by shaunbramley** [comment]
Refences: A. [Guzzle-Rate-Limiter](https://github.com/rtheunissen/guzzle-rate-limiter)

You can manually add a rate limiting middleware to the underlying Guzzle Client.

```
$stack = GuzzleHttp\HandlerStack::create();
$stack->push(new Concat\Http\Middleware\RateLimiter($ImplementationOfRateLimitProvider));

$guzzle = new Guzzle\Client([
    'handler' => $stack,
]);

$client = new Goutte\Client();
$client->setClient($guzzle);
```

**Comment by mattiasghodsian** [comment]
What value should $ImplementationOfRateLimitProvider have ?

`
use Goutte\Client;
use GuzzleHttp\Client as GuzzleClient;
$stack = GuzzleHttp\HandlerStack::create();
$stack->push(new Concat\Http\Middleware\RateLimiter($ImplementationOfRateLimitProvider));

$guzzle = new Guzzle\Client([
    'handler' => $stack,
]);

$client = new Goutte\Client();
$client->setClient($guzzle);


$crawler = $client->request('GET', $url);
$data = array();

	$crawler->filterXPath("//*[@itemprop]")
	    ->each(function($node) use (&$data){
	        $ret = $this->getStructuredData($node);
	        $data[$ret['property']] = $ret['value'];
	        s
`

**Comment by shaunbramley** [comment]
It is an implementation of the `RateLimitProvider` Interface.  Implementations are left for developers to design / develop.  @rtheunissen has a fairly simple implementation as part of the docs (linked in previous response).

**Comment by abhinavkumar940** [comment]
Just curious, what's wrong with using `sleep` ? Why do you want to introduce a whole new lib just to get rid of one line?

**Comment by stof** [comment]
I don't understand why you want to sleep inside the loop over nodes (unless ``getStructuredData`` itself is doing more HTTP requests). the only piece of code contacting the remote server with Goutte in your case is ``$client->request('GET', $url);``

**Comment by abhinavkumar940** [comment]
I kinda missed that but yeah that's a more sensible question.

**Comment by mattiasghodsian** [comment]
@stof Im doing over 1000 request to the same website, i don´t want them to think i´m doing something fishy, and i apologize for been unclear. I wanna slow down the process for the GET not the loop

$client->request('GET', $url);

**Comment by stof** [comment]
Well, then it means you have to slow down your own code, not Goutte, as it is your own code doing the ``->request()`` calls. I don't think the Goutte issue tracker is the right place to ask for that (and using ``sleep`` is a good first step)
