### ISSUE TITLE
No link returned from <div>

### ISSUE THREAD

**Issue by Anan5a** [FriendsOfPHP/Goutte#292]
I'm trying to get data from div tag.
```
...
$crawler->filter('div#content')->each(function($node){
echo $node->text();
});
```
The text data returned but no link or img returned! Why?

**Comment by stof** [comment]
I don't understand what you mean

**Comment by Anan5a** [comment]
I didn't get any <a> or <img> or other tag from that div tough there are links and images

**Comment by stof** [comment]
Well, ``->text()`` will never give you a HTML tag, as it gives you the **text** inside this node, not the HTML markup. If you want the HTML inside this node, use ``getHtml()``

**Comment by Anan5a** [comment]
Thanks.
