### ISSUE TITLE
You can't perform that action at this time on Github login example

### ISSUE THREAD

**Issue by anuj9196** [FriendsOfPHP/Goutte#319]
I tried the login example given in the documentation but it prints
```
You can't perform that action at this time
```

What could be the cause of error?

**Comment by naokwn** [comment]
I had the same problem.

**Comment by osseven** [comment]
I had the same problem

**Comment by cy16f01** [comment]
Even i am having the same issues...I am unable to post any comments/replies or unable to open up any issues..?? Why does this happen..??

Any suggestions on how to solve this issue..??

**Comment by arthurcvm** [comment]
Hello guys, I think I solved it, look the example adjusted:

`use Goutte\Client;

    $client = new Client();
    
    $crawler = $client->request('GET', 'https://github.com/');
    $crawler = $client->click($crawler->selectLink('Sign in')->link());
    $token = $crawler->filter('input')->eq(1)->extract('value')[0];
    $form = $crawler->selectButton('Sign in')->form();
    $crawler = $client->submit($form, array('authenticity_token' => "$token", 'login' => 'YourUserNameHere', 'password' => 'YourPassHere'));
    $crawler->filter('.account-switcher-truncate-override')->each(function ($node) { //Get the username
        print $node->text()."\n";
    });`

**Comment by crensyhanilas** [comment]
It seems that you have blocked.

**Comment by beesfoo** [comment]
At the risk of stating something obvious and not relevant to your issue... I just got this message when attempting to star a project after just creating a new account. Confirming my email address fixed it (and maybe going through the account initialization setup it redirects to, although probably not required).

**Comment by bradyreino** [comment]
@beesfoo Use the link https://github.com/mamedev/mame/issues/7941, then to unban my account on MAMEdev page, write "Unban "bradyreino" on the MAMEdev page.".

**Comment by bradyreino** [comment]
@beesfoo click the link mamedev/mame#7941 and write "Unban "bradyreino".".

**Comment by bradyreino** [comment]
@beesfoo click the link mamedev/mame#7941 and write "Unban "bradyreino"." to comment to MAMEdevs again without banning.

**Comment by bradyreino** [comment]
@beesfoo I can comment to MAMEdevs without banning, to unban me on the MAMEdev page, click the link mamedev/mame#7941 and write "Unban "bradyreino".".

**Comment by qamichele5959** [comment]
UNBAN wiisxrx niuus

**Comment by qamichele5959** [comment]
It seems that you have blocked.

**Comment by stof** [comment]
@fabpot I suggest closing this issue, as it is not about an issue in Goutte (and the recent discussion happening here seems *even less* related to Goutte)

**Comment by PJM-NCC-70511** [comment]
I am getting the same issue. The repository owner should not have a reason to block me because it was the first time I submitted something about an issue with the software.

**Comment by skiyomi** [comment]
for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltasfor yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas
