### ISSUE TITLE
Call to undefined function curl_reset() php 5.4

### ISSUE THREAD

**Issue by lycenok** [FriendsOfPHP/Goutte#324]
I didn't want to risk and install 5.6 on production so 
I temporarily worked around this in 

vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php

            // curl_reset($resource);
            // Not working in PHP 5.4
            $resource = curl_init(); // For PHP 5.4 Lycenok 

used this link
https://stackoverflow.com/questions/25523004/fatal-error-curl-reset-undefined-why

**Comment by stof** [comment]
Well, you cannot use the curl factory of Guzzle if you don't have the `curl` extension installed on your system.

**Comment by stof** [comment]
oh, and the latest version of Goutte does *not* support PHP 5.4 at all.
