### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by prakhargvp** [FriendsOfPHP/Goutte#337]
Using Goutte in Laravel but its not working...

![screenshot from 2018-02-10 17-25-14](https://user-images.githubusercontent.com/7056772/36061895-a2b75580-0e87-11e8-8170-c7d82234a9d0.png)
![screenshot from 2018-02-10 17-26-55](https://user-images.githubusercontent.com/7056772/36061897-a3e16a9a-0e87-11e8-9443-0fd44f687908.png)

**Comment by fabpot** [comment]
It means you are using a version of Goutte that only supports PHP 7+. Please, use an older version.

**Comment by CodeBrauer** [comment]
@fabpot This should be mentioned/changed in the readme -> Symfony now requires PHP 7.1.3 or higher now.

**Comment by stof** [comment]
Composer already handles PHP requirements when selecting packages. Are you installing Goutte using another way ?

**Comment by CodeBrauer** [comment]
My fault:

My CLI uses another php version then my apache does. Didn't notice it was changed.
