### ISSUE TITLE
[Question][Is there anyway to to ignoring images and css when crawling]

### ISSUE THREAD

**Issue by msaus** [FriendsOfPHP/Goutte#338]
Hello there,

I found that it is pretty slow when there are lots of image on the web site.

Is there anyway to crawl only HTML code, not images itself.

Thanks.

**Comment by stof** [comment]
Goutte does *not* load images (unless your own code built on top of it does it).

**Comment by msaus** [comment]
I see.....
Thanks for that.
The reason why I am asking this question is that it seems when I crawl following URL, it is very very slow....
Therefore, I am asking this question.
https://search.rakuten.co.jp/search/mall/baby/?p=1
