### ISSUE TITLE
Goutte on PHP 7.3.3-1+ubuntu18.04 doesn't not work

### ISSUE THREAD

**Issue by flanderboy** [FriendsOfPHP/Goutte#376]
Hello everyone,
I try to execute the crawler on 7.3.3-1+ubuntu18.04 but doesn't not work.
Any suggestion?

Best,
Stefano

**Comment by larowlan** [comment]
Hi 
Can you please provide more information other than 

> does not work

E.g. what were you trying to do, what was the expected result, what was the actual result.

Thanks

**Comment by flanderboy** [comment]
> Hi
> Can you please provide more information other than
> 
> > does not work
> 
> E.g. what were you trying to do, what was the expected result, what was the actual result.
> 
> Thanks
