### ISSUE TITLE
Removing nodes

### ISSUE THREAD

**Issue by damcclean** [FriendsOfPHP/Goutte#377]
Hi,

Is there any way using Goutte to remove nodes? I'm building a parser but I need to remove header and footer elements, along with others.

I've briefly looked at the source code for Symfony Crawler and I found the `reduce` function but I'm unsure on how to use it.

**Comment by NinoSkopac** [comment]
`$node->parentNode->removeChild($node);` will do it :)

**Comment by damcclean** [comment]
Do I put that inside a filter @NinoSkopac?

**Comment by NinoSkopac** [comment]
No, in the callback closure.

**Comment by damcclean** [comment]
Sorry, I don't understand. Do you mind providing an example?

**Comment by damcclean** [comment]
I have just attempted to do this using this code:

```
$crawler
                ->filter('nav, header, #nav, #header')
                ->each(function ($node) use (&$body) {
                    $node->parentNode->removeChild($node);
                });
```

With that I get the error message, `Undefined property: Symfony\Component\DomCrawler\Crawler::$parentNode`

**Comment by stof** [comment]
the argument of the `each` method is a Crawler object, not a DomElement node. You need to get the node out of it.

**Comment by NinoSkopac** [comment]
Exactly, typehint it like this: `function (Crawler $node) { ...calback code... }`

**Comment by NinoSkopac** [comment]
And you can get the node out of it thus: `$node->getNode(0);`

**Comment by damcclean** [comment]
Thanks for your help! Managed to achieve it!

```
$crawler
                ->filter('head, script, nav, header, #nav, #header, .navbar, #navbar, footer, .footer #foorer, .sidebar, #sidebar, .comments, #comments, .pagination, button')
                ->each(function (Crawler $crawler) {
                    foreach ($crawler as $node) {
                        $node->parentNode->removeChild($node);
                    }
                });
```
