### ISSUE TITLE
Cannot get response status code

### ISSUE THREAD

**Issue by andrii-trush** [FriendsOfPHP/Goutte#389]
Hello. I'm trying to get url returns 404 error. 

```php
$goutteClient = new Client();
$response = $goutteClient->setHeader('User-Agent', $userAgent)->setClient($guzzleClient)->request('GET', 'https://example.com');
```

`$response` is instance of `Symfony\Component\DomCrawler\Crawler`

So, how can I get status for checking it is 404?

**Comment by stof** [comment]
`$goutteClient->getResponse()` will give you the Response object of the last request being done (and you should rename your `$response` variable, which is not the response.
