### ISSUE TITLE
Install error on Laravel 6

### ISSUE THREAD

**Issue by khanhvu14** [FriendsOfPHP/Goutte#390]
Problem 1
    - Installation request for fabpot/goutte ^3.2 -> satisfiable by fabpot/goutte[v3.2.0, v3.2.1, v3.2.2, v3.2.3].
    - laravel/framework v6.0.0 requires symfony/http-kernel ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4].
    - laravel/framework v6.0.1 requires symfony/http-kernel ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4].
    - laravel/framework v6.0.2 requires symfony/http-kernel ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4].
    - laravel/framework v6.0.3 requires symfony/http-kernel ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4].
    - laravel/framework v6.0.4 requires symfony/http-kernel ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4].
    - Conclusion: don't install symfony/http-kernel v4.3.4
    - Installation request for laravel/framework 6.0.* -> satisfiable by laravel/framework[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].

**Comment by vipertecpro** [comment]
Can you please provide your composer.json to get core of this ?

**Comment by khanhvu14** [comment]
My mistake, sorry. Thanks
