### ISSUE TITLE
Raise Guzzle version at least to 6.3

### ISSUE THREAD

**Issue by DonCallisto** [FriendsOfPHP/Goutte#393]
I recently found this https://github.com/guzzle/guzzle/issues/1973 that was merged in Guzzle 6.3 so i think we should bump Guzzle version and release a 3.3 version of Goutte.

Any thoughts?

If this is fine, I'm willing to do the necessary work.

**Comment by fabpot** [comment]
Version 6.3 are already supported, there is nothing to do.

**Comment by DonCallisto** [comment]
But version 6.2 got the issue I’ve linked so if I try to test with low deps I encounter the error that’s shown in linked issue.
I’m not stating that you should raise the minimum version because of low deps but because 6.2 has that error that, virtually, makes this library unusable.

**Comment by DonCallisto** [comment]
I've found that with [`conflict` ](https://getcomposer.org/doc/04-schema.md#conflict) I can overcome the issue. Still doubtful about keeping `Guzzle` 6.2 version supported by this library.
