### ISSUE TITLE
Unexpected ? error in Symfony Browser Kit on line 632

### ISSUE THREAD

**Issue by goldhat** [FriendsOfPHP/Goutte#395]
After fresh install (on PHP7.0.10) I got the error below, maybe that version doesn't work for PHP7.x? 

( ! ) Parse error: syntax error, unexpected '?' in C:\wamp64\www\lima\vendor\symfony\browser-kit\Client.php on line 632
--

**Comment by larowlan** [comment]
Php 7.0 (and 7.1) are end of life.

7.1 introduced nullable types - e.g.

`function foo(?bar $whiz): ?bar`

I think that's your issue - you need a supported version of php
