### ISSUE TITLE
Return value of Symfony\Component\DomCrawler\Crawler::createSubCrawler() must be an instance of Symfony\Component\DomCrawler\object, instance of Symfony\Component\DomCrawler\Crawler returned

### ISSUE THREAD

**Issue by marionava** [FriendsOfPHP/Goutte#408]
Hi, I don't know why on my lap everything is working fine and on my server I'm getting this error:

Return value of Symfony\Component\DomCrawler\Crawler::createSubCrawler() must be an instance of Symfony\Component\DomCrawler\object, instance of Symfony\Component\DomCrawler\Crawler returned

<img width="1209" alt="Captura de Pantalla 2020-01-31 a la(s) 18 20 25" src="https://user-images.githubusercontent.com/478018/73583286-f1a1a400-4456-11ea-8d69-e2da0aa251dd.png">

My code is on a Laravel Controller

```
use Goutte\Client;

class DashboardController extends Controller
{
public function getDolarHoy()
    {
        $client = new Client();
        $crawler = $client->request('GET', 'https://www.eldolar.info/es-MX/mexico/dia/hoy');
        $dolarhoy = $crawler->filter('table#dllsTable>tbody>tr>td.xTimes')->eq(1)->text();

        return $dolarhoy;
    }
}
```
The error is on the second line of the function.

On my server I have php 7.2.26 
I'm using "fabpot/goutte": "^4.0"

**Comment by fabdelgado** [comment]
Hi, I've try and it' works in Laravel.

use Goutte\Client as Client;

$client = new Client();
$crawler = $client->request('GET', 'https://www.eldolar.info/es-MX/mexico/dia/hoy');
$dolarhoy = $crawler->filter('table#dllsTable>tbody>tr>td.xTimes')->eq(1)->text();

echo $dolarhoy;

**Comment by fabdelgado** [comment]
Hi, I've try and it' works in Laravel.

use Goutte\Client as Client;

$client = new Client();
$crawler = $client->request('GET',
'https://www.eldolar.info/es-MX/mexico/dia/hoy');
$dolarhoy = $crawler->filter('table#dllsTable>tbody>tr>td.xTimes')->eq(1)->text();

echo $dolarhoy;

**Comment by marionava** [comment]
Sorry, I've review the php server version an is 7.1.24. 

Is this the bug reason?

**Comment by marionava** [comment]
Yes, the php version (7.1.*) is the reason...

It would be great if you edit your Readme.rst to 
```
Goutte depends on PHP 7.2+.
```
