### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates for https://example.com

### ISSUE THREAD

**Issue by Leleking** [FriendsOfPHP/Goutte#437]
I am using this package with laravel. Locally, it works just fine but after deploying to the server I get this error
`Symfony\Component\HttpClient\Exception\TransportException: Peer certificate cannot be authenticated with given CA certificates for https://example.com`

**Comment by Leleking** [comment]
After digging around i found the fix.
use Symfony\Component\HttpClient\HttpClient;

$url = 'https://www.bog.gov.gh/treasury-and-the-markets/daily-interbank-fx-rates/';
        $client  = new Client(HttpClient::create(['verify_peer' => false, 'verify_host'=> false]));
        $crawler = $client->request('GET', $url);

**Comment by stof** [comment]
note that disabling peer verification is insecure though. You should rather make sure that CA certificates are configured properly on your server.
