### ISSUE TITLE
How to bypass captchas and cloudfare protection?

### ISSUE THREAD

**Issue by msouto346** [FriendsOfPHP/Goutte#450]
Hello, I am using this package and in local development it works great... but when on production with a non residencial IP my requests get blocked by cloudfare, for example:

`"Attention Required! | Cloudflare body{margin:0;padding:0} if (!navigator.cookieEnabled)...`

Any way to workaround this? I have googled quite a bit and found nothing that worked.

**Comment by stof** [comment]
Well, if the prod server is protected by Cloudflare's bot protection features, there is nothing you can do as it is legimitate for them to block your bot if you asked it to do it.

**Comment by msouto346** [comment]
> Well, if the prod server is protected by Cloudflare's bot protection features, there is nothing you can do as it is legimitate for them to block your bot if you asked it to do it.

What I am saying is the website I am scraping allows me to do it in my local development (residential ip) but when on production with my digital ocean ip it gets blocked. And I was checking if there is any possible workaround for it. I'm sure there is because I have seen other bots doing this exact same thing (check ps5 stocks from this website).

**Comment by fabpot** [comment]
Not related to Goutte anyway.
