### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by henryonsoftware** [FriendsOfPHP/Goutte#456]
I saw many Issues but no one answer and also no release for a long time.
Is it dead?

**Comment by fabpot** [comment]
It's not dead. Just that all the code has been migrated to Symfony now. So, this project is just a very simple wrapper. See https://github.com/FriendsOfPHP/Goutte/blob/master/Goutte/Client.php

For the issues, most of them are mostly about people looking for support, for which I don't have time, to be honest.
