### ISSUE TITLE
Recent "src/" update breaks Composer install?

### ISSUE THREAD

**Issue by enygma** [FriendsOfPHP/Goutte#47]
I'm trying to install the latest Goutte version via Composer and I keep geting an error that the "Goutte\Client" can't be found. I noticed that there was a recent change that pulled the code out of the "src/" directory. When Composer makes the autoloader, it still tries to include this in the namespacing:

'Goutte' => $vendorDir . '/fabpot/goutte/src/',

If I manually remove it, I get this exception: https://gist.github.com/2704894

Seems like something's broken....not sure what, though.

**Comment by tonystonee** [comment]
Hey @enygma, I'm having this problem right now. How do I fix it?
