### ISSUE TITLE
Disabling ssl certification check

### ISSUE THREAD

**Issue by DylanBowden** [FriendsOfPHP/Goutte#63]
Hi,

According to http://mink.behat.org/#gouttedriver the client can be initiated with an array of zend_http_client options. Since I don't valid certifications on all machines, I have tried to disable certification as follows with no success:

$gouttedriver = new \Behat\Mink\Driver\GoutteDriver(
            new \Behat\Mink\Driver\Goutte\Client(array(
            'curloptions' => array(
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_CERTINFO => false
                ),
            )
        ), array());

Is there a way of doing it that works?

**Comment by antsanchez** [comment]
I couldn't get it to work on Laraveil until I did that:
on vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php change the lines 302 -337 

`if (isset($options['verify'])) {
            if ($options['verify'] === false) {
                unset($conf[CURLOPT_CAINFO]);
                $conf[CURLOPT_SSL_VERIFYHOST] = 0;
                $conf[CURLOPT_SSL_VERIFYPEER] = false;
            } else {
                $conf[CURLOPT_SSL_VERIFYHOST] = 2;
                $conf[CURLOPT_SSL_VERIFYPEER] = true;
                if (is_string($options['verify'])) {
                    $conf[CURLOPT_CAINFO] = $options['verify'];
                    if (!file_exists($options['verify'])) {
                        throw new \InvalidArgumentException(
                            "SSL CA bundle not found: {$options['verify']}"
                        );
                    }
                }
            }
        }`

for that
`unset($conf[CURLOPT_CAINFO]);
 $conf[CURLOPT_SSL_VERIFYHOST] = 0;
 $conf[CURLOPT_SSL_VERIFYPEER] = false;`

**Comment by spagu** [comment]
how to enable behat.yml configs ? should I load it somehow ?

**Comment by Yuri-Failer** [comment]
@babaganoush, 
Tnx, settings for behat.yml works for me.

**Comment by egulhan** [comment]
You do not need to modify core lib. file. It works if you use like the following:

`require('vendor/autoload.php');
use Goutte\Client;

$client = new Client();
use GuzzleHttp\Client as GuzzleClient;

$client->setClient(new GuzzleClient(array(
    // DISABLE SSL CERTIFICATE CHECK
    'verify' => false,
)));`
