### ISSUE TITLE
Allow to override Curl options passed to Guzzle request

### ISSUE THREAD

**Issue by antonbabenko** [FriendsOfPHP/Goutte#69]
Currently curl options are hardcoded in `Client.php`, but sometimes more options have to be set (increase timeout or max. redirects).

Code from `Client.php`:

```
 $guzzleRequest->getCurlOptions()
        ->set(CURLOPT_FOLLOWLOCATION, false)
        ->set(CURLOPT_MAXREDIRS, 0)
        ->set(CURLOPT_TIMEOUT, 30);
```

**Comment by YuvrajHinger** [comment]
Modify your scrapping url.
I did in a way like 
`**`http://www.yuvrajhinger.in`**`
for every domain add **`http://www.`**

It works for me.

Hope it helps you.
